# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_probitCppFatCat_rcpp_hello_world`)
}

probCpp <- function(alfa, beta, f, sigma2) {
    .Call(`_probitCppFatCat_probCpp`, alfa, beta, f, sigma2)
}

logcondcompbetajCpp <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompbetajCpp`, f, beta, alfa, sigma2, y, j)
}

logcondcompfiCpp <- function(f, beta, alfa, sigma2, y, i) {
    .Call(`_probitCppFatCat_logcondcompfiCpp`, f, beta, alfa, sigma2, y, i)
}

logcondcompsigma2jCpp <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompsigma2jCpp`, f, beta, alfa, sigma2, y, j)
}

