# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_probitCppFatCat_rcpp_hello_world`)
}

probProbit <- function(alfa, beta, f, sigma2) {
    .Call(`_probitCppFatCat_probProbit`, alfa, beta, f, sigma2)
}

probLogit <- function(alfa, beta, f, sigma2) {
    .Call(`_probitCppFatCat_probLogit`, alfa, beta, f, sigma2)
}

probNominal <- function(beta, f) {
    .Call(`_probitCppFatCat_probNominal`, beta, f)
}

logcondcompbetajProbit <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompbetajProbit`, f, beta, alfa, sigma2, y, j)
}

logcondcompfiProbit <- function(f, beta, alfa, sigma2, y, i) {
    .Call(`_probitCppFatCat_logcondcompfiProbit`, f, beta, alfa, sigma2, y, i)
}

logcondcompsigma2jProbit <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompsigma2jProbit`, f, beta, alfa, sigma2, y, j)
}

logcondcompbetajLogit <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompbetajLogit`, f, beta, alfa, sigma2, y, j)
}

logcondcompfiLogit <- function(f, beta, alfa, sigma2, y, i) {
    .Call(`_probitCppFatCat_logcondcompfiLogit`, f, beta, alfa, sigma2, y, i)
}

logcondcompsigma2jLogit <- function(f, beta, alfa, sigma2, y, j) {
    .Call(`_probitCppFatCat_logcondcompsigma2jLogit`, f, beta, alfa, sigma2, y, j)
}

logcondcompbetajkNominal <- function(f, beta, y, j, k) {
    .Call(`_probitCppFatCat_logcondcompbetajkNominal`, f, beta, y, j, k)
}

logcondcompfiNominal <- function(f, beta, y, i) {
    .Call(`_probitCppFatCat_logcondcompfiNominal`, f, beta, y, i)
}

